from flask import Flask, session, redirect, url_for
from functools import wraps

from flask.cli import load_dotenv
from pymongo import MongoClient
import os

app = Flask(__name__)
load_dotenv()
# Secret key generated by python
app.config['SECRET_KEY'] = os.environ.get('FLASK_KEY')

# MongoDB DataBase
client = MongoClient(os.getenv("MONGODB_URI"))
db = client.FlaskLoginSystem


# Decorators
def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            return redirect('/')

    return wrap