from flask import Flask, session, redirect, url_for
from functools import wraps
from pymongo import MongoClient
import os

app = Flask(__name__)

# Secret key generated by python
app.config['SECRET_KEY'] = os.environ.get('FLASK_KEY')

# MongoDB DataBase
client = MongoClient('mongodb+srv://beqsproger:GytH8lKO4wIDkHYN@flaskloginsystem.kbi6t.mongodb.net/')
db = client.FlaskLoginSystem


# Decorators
def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            return redirect('/')

    return wrap