from flask import Flask, session, redirect, url_for
from functools import wraps
from pymongo import MongoClient

app = Flask(__name__)

# Secret key generated by python
app.secret_key = b'\xcc^\x91\xea\x17-\xd0W\x03\xa7\xf8J0\xac8\xc5'

# MongoDB DataBase
client = MongoClient('mongodb+srv://beqsproger:GytH8lKO4wIDkHYN@flaskloginsystem.kbi6t.mongodb.net/')
db = client.FlaskLoginSystem


# Decorators
def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            return redirect('/')

    return wrap